version: "3.9"

services:
  streamlit:
    build:
      context: .
      dockerfile: docker/streamlit.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./model/saved_model:/app/model/saved_model:ro
      - ./app:/app/app:ro
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow.db:/mlflow.db 